name: Release Beta

on:
  push:
    branches: [ main ]

jobs:
  release-beta:
    if: |
      !contains(github.event.head_commit.message, '[skip-beta]')
    name: Release Beta
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Push version updates
        run: |
          gh auth login --with-token $GITHUB_TOKEN