name: Release Alpha

on:
  push:
    branches: [ '!main' ]
  pull_request_target:
    types: [ labeled ]

jobs:
  release-alpha:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'alpha') ||
      (github.event.commits && contains(github.event.head_commit.message, '[alpha]'))
    name: Release Alpha
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Switch to branch
        if: github.event.action == 'labeled'
        run: |
          git remote set-url origin ${{ github.event.pull_request.head.repo.clone_url }}
          git fetch
          git checkout ${{ github.head_ref }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set version
        run: |
          echo "NEW_VERSION=$(./scripts/set_version alpha)" >> $GITHUB_ENV
      - name: Install pep517
        run: >-
          python -m
          pip install
          pep517
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          pep517.build
          --source
          --binary
          --out-dir dist/
          .
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Push version updates
        run: |
          git config --global user.name 'GitHub'
          git config --global user.email 'github@users.noreply.github.com'
          git add ./setup.py ./pyproject.toml
          git commit -m "Released $NEW_VERSION to Test PyPI"
          git push