name: Release Beta

on:
  push:
    branches: [ main ]

jobs:
  release-beta:
    if: |
      !contains(github.event.head_commit.message, '[skip-beta]')
    name: Release Beta
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set version
        run: |
          echo "NEW_VERSION=$(./scripts/set_version beta)" >> $GITHUB_ENV
      - name: Install pep517
        run: >-
          python -m
          pip install
          pep517
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          pep517.build
          --source
          --binary
          --out-dir dist/
          .
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Push version updates
        run: |
          git config --global user.name 'GitHub'
          git config --global user.email 'github@users.noreply.github.com'
          CURRENT_BRANCH=$(git branch --show-current)
          git checkout -b release-$NEW_VERSION
          git add ./setup.py ./pyproject.toml
          COMMIT_MESSAGE="Released $NEW_VERSION to Test PyPI"
          git commit -m "$COMMIT_MESSAGE"
          git push --set-upstream origin release-$NEW_VERSION
          gh auth login --with-token $GITHUB_TOKEN
          gh pr create --fill --base $CURRENT_BRANCH
          gh auth login --with-token $GIT_JOCK
          gh pr review --approve
          gh auth login --with-token $GITHUB_TOKEN
          gh pr merge --squash